
R version 4.4.1 (2024-06-14 ucrt) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from C:/Users/shind/Downloads/archive (5)/.RData]

> dflang <- read.csv('languagedata.csv')
> top5 <- read.csv('top5language.csv')
> annual <- read.csv('annualdf.csv')
> annual
ID Rank Programming.Language Ratings Annual.Change
1   2    3               Python   11.72          2.01
2   3    4                  C++    7.56          1.99
3   0    1                    C   17.38          1.61
4   9   10               Groovy    1.84          1.23
5   8    9                    R    1.90          1.10
6  10   11    Assembly language    1.64          0.76
7  13   14                   Go    1.41          0.51
8  15   16               MATLAB    1.15          0.41
9  16   17                 Perl    1.02          0.27
10 14   15                 Ruby    1.30          0.24
11 11   12                  SQL    1.61          0.10
12 17   18          Objective-C    1.00          0.07
13 19   20 Classic Visual Basic    0.79         -0.04
14 18   19 Delphi/Object Pascal    0.79         -0.20
15  6    7           JavaScript    2.20         -0.25
16 12   13                Swift    1.43         -0.36
17  7    8                  PHP    1.99         -0.41
18  4    5                   C#    3.95         -1.40
19  5    6         Visual Basic    3.84         -1.44
20  1    2                 Java   11.96         -4.93
> dflang
ID Rank Programming.Language Ratings Annual.Change
1  19   20 Classic Visual Basic    0.79         -0.04
2  18   19 Delphi/Object Pascal    0.79         -0.20
3  17   18          Objective-C    1.00          0.07
4  16   17                 Perl    1.02          0.27
5  15   16               MATLAB    1.15          0.41
6  14   15                 Ruby    1.30          0.24
7  13   14                   Go    1.41          0.51
8  12   13                Swift    1.43         -0.36
9  11   12                  SQL    1.61          0.10
10 10   11    Assembly language    1.64          0.76
11  9   10               Groovy    1.84          1.23
12  8    9                    R    1.90          1.10
13  7    8                  PHP    1.99         -0.41
14  6    7           JavaScript    2.20         -0.25
15  5    6         Visual Basic    3.84         -1.44
16  4    5                   C#    3.95         -1.40
17  3    4                  C++    7.56          1.99
18  2    3               Python   11.72          2.01
19  1    2                 Java   11.96         -4.93
20  0    1                    C   17.38          1.61
> top5
ID Rank Programming.Language Ratings Annual.Change
1 19   20 Classic Visual Basic    0.79         -0.04
2 18   19 Delphi/Object Pascal    0.79         -0.20
3 17   18          Objective-C    1.00          0.07
4 16   17                 Perl    1.02          0.27
5 15   16               MATLAB    1.15          0.41
> barplot(top5)
Error in barplot.default(top5) : 'height' must be a vector or a matrix
> barplot(top5$Programming.Language)
Error in -0.01 * height : non-numeric argument to binary operator
> barplot(top5$Ratings)
> barplot(top5$Ratings, title='Programming Languages with Top 5 Ratings')
Warning messages:
  1: In plot.window(xlim, ylim, log = log, ...) :
  "title" is not a graphical parameter
2: In title(main = main, sub = sub, xlab = xlab, ylab = ylab, ...) :
  "title" is not a graphical parameter
3: In axis(if (horiz) 1 else 2, cex.axis = cex.axis, ...) :
  "title" is not a graphical parameter
> barplot(top5$Ratings, main='5 Languages with Highest Ratings')
Warning messages:
  1: In doTryCatch(return(expr), name, parentenv, handler) :
  "title" is not a graphical parameter
2: In doTryCatch(return(expr), name, parentenv, handler) :
  "title" is not a graphical parameter
3: In doTryCatch(return(expr), name, parentenv, handler) :
  "title" is not a graphical parameter
4: In doTryCatch(return(expr), name, parentenv, handler) :
  "title" is not a graphical parameter
5: In doTryCatch(return(expr), name, parentenv, handler) :
  "title" is not a graphical parameter
6: In doTryCatch(return(expr), name, parentenv, handler) :
  "title" is not a graphical parameter
> barplot(top5$Ratings, main='5 Languages with Highest Ratings', xlab='Language', ylab='Rating')
> barplot(top5$Ratings, main='5 Languages with Highest Ratings', xlab='Language', ylab='Rating', names.arg=top5$Programming.Language)
> real_top5 <- head(dflang$Ratings, 5)
> real_top5
[1] 0.79 0.79 1.00 1.02 1.15
> barplot(real_top5)
> real_top5 <- tail(dflang$Ratings, 5)
> real_top5
[1]  3.95  7.56 11.72 11.96 17.38
> barplot(real_top5, main='5 Languages with Highest Ratings', ylab='Rating', names.arg=tail(dflang$Programming.Language, 5))
> barplot(tail(dflang$Ratings), main='Top Languages by User Preferance', ylab'Rating', names.arg=tail(dflang$Programming.Language))
Error: unexpected string constant in "barplot(tail(dflang$Ratings), main='Top Languages by User Preferance', ylab'Rating'"
> barplot(tail(dflang$Ratings, 20), main='Top Languages by User Preferance', ylab'Rating', names.arg=tail(dflang$Programming.Language, 20))
Error: unexpected string constant in "barplot(tail(dflang$Ratings, 20), main='Top Languages by User Preferance', ylab'Rating'"
> barplot(dflang$Ratings, main='Top Languages by User Preferance', ylab'Rating', names.arg=dflang$Programming.Language)
Error: unexpected string constant in "barplot(dflang$Ratings, main='Top Languages by User Preferance', ylab'Rating'"
> pie(dflang$Ratings, names.arg=dflang$Programming.Language)
There were 21 warnings (use warnings() to see them)
> pie(real_top5, names.arg=dflang$Programming.Language, main='Top 5 Popular Languages')
There were 48 warnings (use warnings() to see them)
> legend('topright', legend=dflang$Programming.Language, fill=rainbow(length(dflang$Ratings)))
There were 12 warnings (use warnings() to see them)
> real_top5 <- tail(dflang, 5)
There were 12 warnings (use warnings() to see them)
> real_top5
ID Rank Programming.Language Ratings Annual.Change
16  4    5                   C#    3.95         -1.40
17  3    4                  C++    7.56          1.99
18  2    3               Python   11.72          2.01
19  1    2                 Java   11.96         -4.93
20  0    1                    C   17.38          1.61
> pie(real_top5, names.arg=real_top5$Programming.Language, main='Top 5 Popular Languages')
Error in pie(real_top5, names.arg = real_top5$Programming.Language, main = "Top 5 Popular Languages") : 
  'x' values must be positive.
> pie(real_top5$Ratings, names.arg=real_top5$Programming.Language, main='Top 5 Popular Languages')
Warning messages:
  1: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                 "names.arg" is not a graphical parameter
                                                                               2: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                              "names.arg" is not a graphical parameter
                                                                                                                                                            3: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                           "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                         4: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                                                                                                        "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                      5: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                                                                                                                                                                                     "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                   6: In title(main = main, ...) : "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                   > legend('topright', legend=real_top5$Programming.Language, fill=rainbow(length(real_top5$Ratings)))
                                                                                                                                                                                                                                                                                                                                                                                                   There were 12 warnings (use warnings() to see them)
                                                                                                                                                                                                                                                                                                                                                                                                   > pie(real_top5$Ratings, names.arg=real_top5$Programming.Language, main='Top 5 Popular Languages', col=colors)
                                                                                                                                                                                                                                                                                                                                                                                                   Error in rep_len(col, nx) : attempt to replicate non-vector
                                                                                                                                                                                                                                                                                                                                                                                                   In addition: There were 12 warnings (use warnings() to see them)
                                                                                                                                                                                                                                                                                                                                                                                                   > pie(real_top5$Ratings, names.arg=real_top5$Programming.Language, main='Top 5 Popular Languages', col=rainbow(length(real_top5$Ratings)))
                                                                                                                                                                                                                                                                                                                                                                                                   Warning messages:
                                                                                                                                                                                                                                                                                                                                                                                                     1: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  2: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            4: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         5: In text.default(1.1 * P$x, 1.1 * P$y, labels[i], xpd = TRUE, adj = ifelse(P$x <  :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      6: In title(main = main, ...) : "names.arg" is not a graphical parameter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > legend("topright", legend=real_top5$Programming.Language, fill=rainbow(length(real_top5$Ratings)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      There were 12 warnings (use warnings() to see them)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > plot(dflang$Programming.Language, dflang$Ratings, main='Ratings for Programming Languages', col='blue')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Error in plot.window(...) : need finite 'xlim' values
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      In addition: There were 15 warnings (use warnings() to see them)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > plot(dflang$ID, dflang$Ratings, main='Ratings for Programming Languages', col='blue')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > plot(dflang$ID, dflang$Ratings, main='Ratings for Programming Languages', col='blue', xlab='Languages', ylab='Average User Rating')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > model <- lm(dflang$Ratings~dflang$ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > abline(model,col='red')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > coef(model)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (Intercept)   dflang$ID 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      9.638143   -0.612015 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > plot(dflang$ID, dflang$Annual.Change, main='Change in Ratings for Programming Languages', col='blue', xlab='Languages', ylab='Annual Change in Preferance')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > model <- lm(dflang$Annual.Change~dflang$ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > > abline(model,col='red')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Error: unexpected '>' in ">"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > model <- lm(dflang$Annual.Change~dflang$ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > abline(model,col='red')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > coef(model)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (Intercept)   dflang$ID 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      -0.18457143  0.02611278 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > dflang
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ID Rank Programming.Language Ratings Annual.Change
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1  19   20 Classic Visual Basic    0.79         -0.04
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2  18   19 Delphi/Object Pascal    0.79         -0.20
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      3  17   18          Objective-C    1.00          0.07
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      4  16   17                 Perl    1.02          0.27
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      5  15   16               MATLAB    1.15          0.41
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      6  14   15                 Ruby    1.30          0.24
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      7  13   14                   Go    1.41          0.51
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      8  12   13                Swift    1.43         -0.36
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      9  11   12                  SQL    1.61          0.10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      10 10   11    Assembly language    1.64          0.76
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      11  9   10               Groovy    1.84          1.23
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      12  8    9                    R    1.90          1.10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      13  7    8                  PHP    1.99         -0.41
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      14  6    7           JavaScript    2.20         -0.25
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      15  5    6         Visual Basic    3.84         -1.44
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      16  4    5                   C#    3.95         -1.40
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      17  3    4                  C++    7.56          1.99
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      18  2    3               Python   11.72          2.01
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      19  1    2                 Java   11.96         -4.93
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      20  0    1                    C   17.38          1.61
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > annualdf
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Error: object 'annualdf' not found
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > annual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ID Rank Programming.Language Ratings Annual.Change
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1   2    3               Python   11.72          2.01
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2   3    4                  C++    7.56          1.99
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      3   0    1                    C   17.38          1.61
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      4   9   10               Groovy    1.84          1.23
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      5   8    9                    R    1.90          1.10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      6  10   11    Assembly language    1.64          0.76
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      7  13   14                   Go    1.41          0.51
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      8  15   16               MATLAB    1.15          0.41
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      9  16   17                 Perl    1.02          0.27
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      10 14   15                 Ruby    1.30          0.24
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      11 11   12                  SQL    1.61          0.10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      12 17   18          Objective-C    1.00          0.07
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      13 19   20 Classic Visual Basic    0.79         -0.04
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      14 18   19 Delphi/Object Pascal    0.79         -0.20
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      15  6    7           JavaScript    2.20         -0.25
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      16 12   13                Swift    1.43         -0.36
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      17  7    8                  PHP    1.99         -0.41
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      18  4    5                   C#    3.95         -1.40
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      19  5    6         Visual Basic    3.84         -1.44
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      20  1    2                 Java   11.96         -4.93
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > barplot(annual$Annual.Change, col='purple', main='Top 5 Languages with Recent Growth in Popularity', names.arg=annual$Programming.Language, ylab='Annual Change')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > barplot(head(annual$Annual.Change,5), col='purple', main='Top 5 Languages with Recent Growth in Popularity', names.arg=annual$Programming.Language, ylab='Annual Change')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Error in barplot.default(head(annual$Annual.Change, 5), col = "purple",  : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 incorrect number of names
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               > barplot(head(annual$Annual.Change,5), col='purple', main='Top 5 Languages with Recent Growth in Popularity', names.arg=annual$Programming.Language, ylab='Annual Change')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Error in barplot.default(head(annual$Annual.Change, 5), col = "purple",  : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          incorrect number of names
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        > barplot(annual$Annual.Change, col='purple', main='Top 5 Languages with Recent Growth in Popularity', names.arg=annual$Programming.Language, ylab='Annual Change')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        > topchange <- head(annual,5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        > barplot(topchange$Annual.Change, col='purple', main='Top 5 Languages with Recent Growth in Popularity', names.arg=topchange$Programming.Language, ylab='Annual Change')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        > bottomchange <- tail(annual,5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        > barplot(bottomchange$Annual.Change, col='purple', main='Least 5 Languages by Recent Growth in Popularity', names.arg=bottomchange$Programming.Language, ylab='Annual Change')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        > annual_real <- subset(annual, select=c(annual$Programming.Language, annual$Annual.Change))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Error in `[.data.frame`(x, r, vars, drop = drop) : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          undefined columns selected
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        > annual_real <- subset(annual, select=c(annual$ID, annual$Annual.Change))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Error in x[j] : only 0's may be mixed with negative subscripts
> annual_real <- subset(annual, select=c(Programming.Language, Annual.Change))
> annual_real
   Programming.Language Annual.Change
1                Python          2.01
2                   C++          1.99
3                     C          1.61
4                Groovy          1.23
5                     R          1.10
6     Assembly language          0.76
7                    Go          0.51
8                MATLAB          0.41
9                  Perl          0.27
10                 Ruby          0.24
11                  SQL          0.10
12          Objective-C          0.07
13 Classic Visual Basic         -0.04
14 Delphi/Object Pascal         -0.20
15           JavaScript         -0.25
16                Swift         -0.36
17                  PHP         -0.41
18                   C#         -1.40
19         Visual Basic         -1.44
20                 Java         -4.93
> model <- lm(annual$Ratings~annual$Annual.Change)
> summary(model)

Call:
lm(formula = annual$Ratings ~ annual$Annual.Change)

Residuals:
   Min     1Q Median     3Q    Max 
-3.051 -2.547 -2.024 -0.052 13.655 

Coefficients:
                     Estimate Std. Error t value Pr(>|t|)   
(Intercept)           3.82806    1.06654   3.589   0.0021 **
annual$Annual.Change -0.06393    0.72564  -0.088   0.9308   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.765 on 18 degrees of freedom
Multiple R-squared:  0.0004311,	Adjusted R-squared:  -0.0551 
F-statistic: 0.007763 on 1 and 18 DF,  p-value: 0.9308

> model <- lm(annual$Ratings~annual$Annual.Change+annual$Programming.Language)
> summary(model)

Call:
lm(formula = annual$Ratings ~ annual$Annual.Change + annual$Programming.Language)

Residuals:
ALL 20 residuals are 0: no residual degrees of freedom!

Coefficients: (1 not defined because of singularities)
                                                Estimate Std. Error t value
(Intercept)                                         2.40        NaN     NaN
annual$Annual.Change                               -1.00        NaN     NaN
annual$Programming.LanguageC                       16.59        NaN     NaN
annual$Programming.LanguageC#                       0.15        NaN     NaN
annual$Programming.LanguageC++                      7.15        NaN     NaN
annual$Programming.LanguageClassic Visual Basic    -1.65        NaN     NaN
annual$Programming.LanguageDelphi/Object Pascal    -1.81        NaN     NaN
annual$Programming.LanguageGo                      -0.48        NaN     NaN
annual$Programming.LanguageGroovy                   0.67        NaN     NaN
annual$Programming.LanguageJava                     4.63        NaN     NaN
annual$Programming.LanguageJavaScript              -0.45        NaN     NaN
annual$Programming.LanguageMATLAB                  -0.84        NaN     NaN
annual$Programming.LanguageObjective-C             -1.33        NaN     NaN
annual$Programming.LanguagePerl                    -1.11        NaN     NaN
annual$Programming.LanguagePHP                     -0.82        NaN     NaN
annual$Programming.LanguagePython                  11.33        NaN     NaN
annual$Programming.LanguageR                        0.60        NaN     NaN
annual$Programming.LanguageRuby                    -0.86        NaN     NaN
annual$Programming.LanguageSQL                     -0.69        NaN     NaN
annual$Programming.LanguageSwift                   -1.33        NaN     NaN
annual$Programming.LanguageVisual Basic               NA         NA      NA
                                                Pr(>|t|)
(Intercept)                                          NaN
annual$Annual.Change                                 NaN
annual$Programming.LanguageC                         NaN
annual$Programming.LanguageC#                        NaN
annual$Programming.LanguageC++                       NaN
annual$Programming.LanguageClassic Visual Basic      NaN
annual$Programming.LanguageDelphi/Object Pascal      NaN
annual$Programming.LanguageGo                        NaN
annual$Programming.LanguageGroovy                    NaN
annual$Programming.LanguageJava                      NaN
annual$Programming.LanguageJavaScript                NaN
annual$Programming.LanguageMATLAB                    NaN
annual$Programming.LanguageObjective-C               NaN
annual$Programming.LanguagePerl                      NaN
annual$Programming.LanguagePHP                       NaN
annual$Programming.LanguagePython                    NaN
annual$Programming.LanguageR                         NaN
annual$Programming.LanguageRuby                      NaN
annual$Programming.LanguageSQL                       NaN
annual$Programming.LanguageSwift                     NaN
annual$Programming.LanguageVisual Basic               NA

Residual standard error: NaN on 0 degrees of freedom
Multiple R-squared:      1,	Adjusted R-squared:    NaN 
F-statistic:   NaN on 19 and 0 DF,  p-value: NA

> summary(aov(annual$Annual.Change))
Error in x$terms : $ operator is invalid for atomic vectors
> summary(aov(annual$Annual.Change~annual$ID))
            Df Sum Sq Mean Sq F value Pr(>F)
annual$ID    1   0.45  0.4534   0.191  0.667
Residuals   18  42.67  2.3707               
> pairwise''
Error: unexpected string constant in "pairwise''"
> pairwise.t.test(annual$Annual.Change, annual$ID, p.adjust.method='Bonferroni')
Error in match.arg(p.adjust.method) : 
  'arg' should be one of “holm”, “hochberg”, “hommel”, “bonferroni”, “BH”, “BY”, “fdr”, “none”
> pairwise.t.test(annual$Annual.Change, annual$ID, p.adjust.method='bonferroni')

	Pairwise comparisons using t tests with pooled SD 

data:  annual$Annual.Change and annual$ID 

   0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
1  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
2  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
3  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
4  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
5  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
6  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
7  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
8  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
9  - - - - - - - - - - -  -  -  -  -  -  -  -  - 
10 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
11 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
12 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
13 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
14 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
15 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
16 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
17 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
18 - - - - - - - - - - -  -  -  -  -  -  -  -  - 
19 - - - - - - - - - - -  -  -  -  -  -  -  -  - 

P value adjustment method: bonferroni 